/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_example_slrs_offline_RecognitionService_ServiceBinder */

#ifndef _Included_com_example_slrs_offline_RecognitionService_ServiceBinder
#define _Included_com_example_slrs_offline_RecognitionService_ServiceBinder
#ifdef __cplusplus
extern "C" {
#endif
#ifdef __cplusplus
}
#endif
#endif
