/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class tw_edu_ntust_jojllman_wearableapplication_BLE_RecognitionService_ServiceBinder */

#ifndef _Included_tw_edu_ntust_jojllman_wearableapplication_BLE_RecognitionService_ServiceBinder
#define _Included_tw_edu_ntust_jojllman_wearableapplication_BLE_RecognitionService_ServiceBinder
#ifdef __cplusplus
extern "C" {
#endif
#ifdef __cplusplus
}
#endif
#endif
