/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class tw_edu_ntust_jojllman_wearableapplication_BLE_RecognitionService */

#ifndef _Included_tw_edu_ntust_jojllman_wearableapplication_BLE_RecognitionService
#define _Included_tw_edu_ntust_jojllman_wearableapplication_BLE_RecognitionService
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     tw_edu_ntust_jojllman_wearableapplication_BLE_RecognitionService
 * Method:    initialize
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_tw_edu_ntust_jojllman_wearableapplication_BLE_RecognitionService_initialize
  (JNIEnv *, jobject);

/*
 * Class:     tw_edu_ntust_jojllman_wearableapplication_BLE_RecognitionService
 * Method:    reset
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_tw_edu_ntust_jojllman_wearableapplication_BLE_RecognitionService_reset
  (JNIEnv *, jobject);

/*
 * Class:     tw_edu_ntust_jojllman_wearableapplication_BLE_RecognitionService
 * Method:    pass_data
 * Signature: ([F[F)V
 */
JNIEXPORT void JNICALL Java_tw_edu_ntust_jojllman_wearableapplication_BLE_RecognitionService_pass_1data
  (JNIEnv *, jobject, jfloatArray, jfloatArray);

/*
 * Class:     tw_edu_ntust_jojllman_wearableapplication_BLE_RecognitionService
 * Method:    run_recognize
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_tw_edu_ntust_jojllman_wearableapplication_BLE_RecognitionService_run_1recognize
  (JNIEnv *, jobject);

/*
 * Class:     tw_edu_ntust_jojllman_wearableapplication_BLE_RecognitionService
 * Method:    getString
 * Signature: ()[B
 */
JNIEXPORT jbyteArray JNICALL Java_tw_edu_ntust_jojllman_wearableapplication_BLE_RecognitionService_getString
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
